version: '2'

services:
  db:
    image: linuxserver/mariadb:arm32v7-latest
    environment:
      MYSQL_ROOT_PASSWORD: fn4e5wfrr
      MYSQL_USER: dsfjhija
      MYSQL_PASSWORD: uf4s4f45f
      MYSQL_DATABASE: filerun_database
    restart: always

  web:
    build: https://github.com/yashichi05/filerun.git
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun_database
      FR_DB_USER: dsfjhija
      FR_DB_PASS: uf4s4f45f
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "80:80"
    volumes:
      - /:/user-files
    restart: always
