version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: fn4e5wfrr
      MYSQL_USER: dsfjhija
      MYSQL_PASSWORD: uf4s4f45f
      MYSQL_DATABASE: filerun_database
    volumes:
      - /filerun/db:/var/lib/mysql

  web:
     build: https://github.com/yashichi05/filerun.git
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun_database
      FR_DB_USER: dsfjhija
      FR_DB_PASS: uf4s4f45f
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "80:80"
    volumes:
      - /filerun/html:/var/www/html
      - /filerun/user-files:/user-files
